int input_array_str(int *arr, char *line, int *pos);
int sommaArray(int *arr, int imax);
void somma2Array(int *arr1, int *arr2, int *imax1, int *imax2);
void outputArray(int *a, int n);
int getresult(char *line);
int controlloOracleArray(int *arr, int *oracle, int imax);
int sumProd(int *arr1, int *arr2, int imax);
int *input_array_dyn(int *size, char *line);
int adaptiveBubbleSort(int *a, int n);
int *concatena_vet(int *a, int *b, int n1, int n2, int *n3);