link: main.o item.o libro.o libreria.o list.o
	gcc main.o item.o libro.o libreria.o list.o -o main.exe

main.o:
	gcc -c main.c

item.o:
	gcc -c item.c

list.o:
	gcc -c list.c

libro.o:
	gcc -c libro.c

libreria.o:
	gcc -c libreria.c

clean:
	rm -f *.o *.exe